# Generated by Django 5.2.8 on 2025-11-22 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car0', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('id_number', models.CharField(help_text='NID or Passport number', max_length=100)),
                ('driving_license_number', models.CharField(blank=True, max_length=100)),
                ('driving_license_photo', models.ImageField(blank=True, null=True, upload_to='bookings/licenses/')),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='bookings/clients/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car0.car')),
            ],
        ),
    ]
