# Generated by Django 5.2.8 on 2025-11-25 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car0', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='request_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy'), ('cancel', 'Cancel Request')], default='rent', max_length=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_assistant_executive',
            field=models.BooleanField(default=False),
        ),
    ]
