# Generated by Django 5.2.8 on 2025-11-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car0', '0004_booking_processed_at_booking_processed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_passenger',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
    ]
