# Generated by Django 5.2.8 on 2025-11-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car0', '0005_remove_customuser_is_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
